#!/bin/bash 

# Extract the detections results generated by SSD to use it for evaluation with caltech code

rm -rf set*
while read line
do
	l=$(echo $line | grep -o 'set[0-9]\+\|V[0-9]\+\|I[0-9]\+\|0.[0-9]\+\|[0-9]\+\|[0-9]\+\|[0-9]\+\|[0-9]\+\n')
	read set vid frame score xmin ymin xmax ymax <<<$(echo $l)
	let width=$xmax-$xmin
	let height=$ymax-$ymin
	if [ ! -d $set ]; then
		mkdir $set
	fi
	if [ ! -d $set/$vid ]; then
		echo $set/$vid
		mkdir $set/$vid
	fi
	echo $xmin $ymin $width $height $score >> $set/$vid/$frame.txt
done < comp4_det_test_person.txt
